codymikol/karma-webpack

README.md

Plugins starting with `karma-` are auto-incuded
Fixes #46

Remove plugin section from example

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
LICENSE

chore(docs) Add Issue/PR templates, Contributing docs and LICENSE

---

README.md

Template pulled in from https://github.com/michael-ciniawsky/README

chore(docs) Update README and change to match template from html5-loader

---

index.js

Fix #146. Docs/Tests untouched.
Minimum-Viable Examples (MVE) for problem and solution detailed in the issue.
I'm apprehensive about this PR:  I don't understand how this fix works. In fact, I feel like I'm taking crazy pills, because the fix simply changes the order of parameters and comments. To be fair, the parameters appear to be meta data (as changing their content also leads to errors). If anyone knows exactly what's going on, I would love a clarification on what those comments are.

Fix 146 - no provider errors

---

index.js

Fix for #151 - TypeError: callback is not a function

---

package.json
webpack.config.babel.js

one build command
Two `build:dev` and `build:dist`
Seperate builds out, dist minifies and remove comments where as dev is pretty raw

chore(build): create seperate builds for dev and dist

---

README.md

- [ x ] Other... Please describe: docs typo
- [ x ] No
* Impact:
Typo on README - one word change

docs(README): One word typo fix

---

src/karma-webpack.js

Fix: Webpack rc4 entry specific changes (fixes #193)

---

src/karma-webpack.js

Chore: lint fixes

---

package.json

Updates peerDependencies to include all beta.x & rc.x versions

chore(package): update webpack peerDependencies

---

.travis.yml

Currently executing validations against out of date webpack versions
Update to test against `2.2.0-rc.4` & `v1.14.0` using Webpacks supported NodeJS versions

ci(Travis): update test matrix

---

src/karma-webpack.js

With auto watch enabled, add a new test after the initial rest run and it will throw.
Reproducible here. Thanks @Silviu-Marian
https://github.com/Silviu-Marian/karma-webpack-pr69
Added a try/catch clause to guard against a "Path doesn't exist" error
coming from `MemoryFileSystem.prototype.readFileSync` when a new file is
added to the file-system that matches the files glob.
* Impact:
* …

fix(readFile): handle path doesn't exist error for new file

---

LICENSE

Karma Webpack is using an outdate license.
Updated to use the proper JSFoundation license

docs(license): JS Foundation standard license

---

src/karma-webpack.js

Configuration / Schema errors from ajv are swallowed by karma-webpack making debugging difficult.
Options is wrapped in a try / catch & throws a stack & or details 
* Impact:
* Github Issue(s) this is regarding: Closes #227 

fix: don't swallow configuration errors

---

package.json

chore(package): update `peerDependencies` (`webpack v3.0.0`)

---

RELEASE.md

updating header markdown
* Impact:

docs(RELEASE): fix spacing

---

README.md

Badges in readme references unknown projects
Badges in readme references the correct project and displays right information
* Impact:

docs: update badge references

---

README.md

**What kind of change does this PR introduce?**
**What is the current behavior?** 
README points to WebPack 1.x docs
README points to latest WebPack docs

docs(README): update link to latest docs (`webpack.js.org`)

---

package.json

- Fixes #268
> ℹ️   edited by @michael-ciniawsky (Formatting)

chore(package): `webpack-dev-middleware` v1.0.11...1.12.0

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/karma-webpack.js
src/mocha-env-loader.js

Mattlewis92 disable watch on single run

---

src/karma-webpack.js

`customFileHanlder` does not handle any files due to bug in `urlRegex` regular expression
In my case it broke test where i use **file-loader** plugin 
should fix issues: #289 #291 for **Linux and OSX** users 
Windows OS require another fix, due to issue with `os.tmpdir()`(see https://github.com/webpack-contrib/karma-webpack/issues/291#issuecomment-353537393)
Fixed regular expression for `customFileHandle`:
- removed the trailing "/"  character that caused the error
- removed unneeded escape symbols
- added function to escape `publicPath` string. …

fix(karma-webpack): correctly escape `{Regex}` in custom file handler

---

package.json

build(package): don't generate source maps for release (`build:release`)

---

.gitignore
src/karma-webpack.js
src/mocha-env-loader.js

style(src/): fix linting errors

---

package.json

fix(package): repository URL typo

---

package-lock.json
package.json

- Fixes #307 
**What kind of change does this PR introduce?**

fix(package): add `babel-runtime` (`devDependencies`)

---

src/karma-webpack.js

Based on my test, this place still needs to add `normalize`
- Fixes #350

fix(karma-webpack): normalize `file.path` (`windows`)

---

CHANGELOG.md
package-lock.json
package.json

`licence/cla` won't let me push directly to master. Trying through a PR...

chore(release): 4.0.0-rc.4

---

package-lock.json
package.json
src/karma-webpack.js

This fixes a regression introduced in [4.0.0-rc4] 
See #390 for details

fix(karma-webpack): Regression in multi-compiler mode (#390)

---

src/karma-webpack.js

- [*] **code refactor**
Fix linting error

refactor(karma-webpack): fix linting error

---

.circleci/config.yml
package.json

Drop node v6 support to match other webpack plugins

chore(package): drop node v6 support

---

package.json

Add more keywords for discoverability in npm. Closes #397.

refactor(package): add more keywords for npm

---

lib/karma-webpack/controller.js

specify correct default filename
Fixes N/A
N/A
N/A

fix(docs): fixed warning inaccuracy

---

package.json

we now only support 10 and up
Fixes N/A
N/A
N/A

fix(docs): use correct node version

---

lib/karma-webpack/controller.js

Solves [#529](https://github.com/ryanclark/karma-webpack/issues/529) by removing the duplicated logging in replacement of the toString variant.
N/A

Remove duplicate webpack error logs.

---

.babelrc
.github/workflows/test.js.yml
package-lock.json
package.json
test/unit/karma-webpack/controller.test.js

this updates dependencies to be up to date for 2023 this many packages with major version changes will result in a major version bump for karma-webpack.
Relates to #552

chore(deps): bring project up to date

---

package.json

chore: upgrade minimatch one major verision

---

package.json

despite the breaking changes, this all still works fine
Fixes N/A

chore: update standard-version

---

package.json

chore: update webpack-contrib-defaults

---

package-lock.json
package.json

these are unused and just cause auditing issues
Fixes N/A

chore: remove del / del-cli

---

package-lock.json
package.json

chore: upgrade karma-mocha

---

package-lock.json
package.json

it seems this package is replaced, I'll seek guidance on  whatever the current release process is and go from there.
Fixes N/A

chore: remove github releaser

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 5.0.1
