codymikol/karma-webpack

README.md, example/karma.conf.js, index.js, mocha-env-loader.js, package.json
All of the compiler setup and plugin operations were assuming a singular Compiler instance vs. MultiCompiler constructs. This changes the behavior to allow for iteration over multiple compilers where necessary.
Fixes #31
=> Update to properly handle MultiCompiler instances

README.md, index.js, package.json
The prior solution of pushing all content to the to the webpack server broke down for globs and watching. Karma really desires files and also prefers one to one mapping of said files and trying to fight that was not fruitful.
Instead opted to move all entry points back to the normal Karma serving routes and any auxiliary resources through the middleware.
This also removes much of the complexity and potential overhead relating to tracking individual file changes as Karma does not seem to do incremental testing and a filelist refresh will ensure that the rebuild occurs.
Fixes #1
=> Utilize webpack-dev-middleware for hosting

index.js, package.json
So yesterday I was pulling my hair out: _why_ the hell were my Karma config options changing when I ran `gulp-karma` **before** I then ran `gulp-webpack` with the same options object. I then dived into this code and saw that the object arguments being passed are being manipulated. Super sad times.
So what I've done is simply used lodash's `_.clone` so that this plugin's magic doesn't mess with my magic and we're all happy; I hope that's ok.
=> Added lodash to clone reference options

index.js, package.json
I've just released `0.13.2` which adds a public api, that avoids having the breakage that was experienced with the upgrade to `0.13.0`
Closes #62, https://github.com/karma-runner/karma/issues/1497
=> Upgrade to use the new public karma api for refreshing files

.editorconfig, .eslintrc, .jsbeautifyrc, index.js, mocha-env-loader.js, package.json
- Adds editorconfig
- Adds eslint package and config
- Adds jsBeautify and config
- Adds lint npm script
- Adds beautify-lint npm script
- Adds pretest npm script to exec linting
- Fixes existing linting errors
Note: Executed in pretest for consistency with other loaders under the assumption tests are coming soon.
Resolves #142
=> chore(style): Bring code quality tooling inline with Webpack

index.js
Without this change trying to access a chunk inside a test will result in a 404 and a very cryptic test error.
=> Support chunks without errors

README.md
see https://github.com/webpack/webpack/issues/1191 - noInfo: true did not work
=> silence webpack output using stats: 'errors-only'

index.js, package.json
Will fix error thrown by webpack 2.1.0-beta.7+ and support through beta-15 (latest). Resolves #117
=> Add support for webpack@2.1.0-beta

README.md, index.js
When you make a code change and then refresh karma, sometimes karma will serve the old test files (because webpack is recompiling). This behavior can become annoying and waste time.
This change adds an optional middleware that will block karma from serving the test files until the build is complete.
Note that the middleware needs to be injected before karma's middleware, which is in this PR: https://github.com/karma-runner/karma/pull/2143
We should hold off on merging until the karma PR above is merged.
=> Adding webpack blocker to stop karma from running tests until build is finished

README.md
This prevents specs from running twice every time a file changes, because karma-webpack already triggers a rerun when recompiled.
Thanks to this comment: https://github.com/webpack/karma-webpack/issues/44#issuecomment-133619802
=> Do not let karma watch files on the example

CHANGELOG.md, CONTRIBUTING.md, package.json, scripts/release/generate-changelog.js
Adds a version changelog
* Impact:
- Implements conventional-changelog w/ commitizen adapter
- Updates `Contributing.md` with setup & commit message instructions
=> Adds project changelog

README.md
* Impact:
karma loads all plugins with 'karma-' automatically, including 'plugins' property in config leads to cryptic error messages when attempting to run karma.
=> remove plugins property from README example

.npmignore, package.json, scripts/release/README.md, scripts/release/npm-publish.sh
Publishing was a completely manual process.
An authorized user can execute a single npm command to push a new tag to the npm registry
* Impact: None - Internal Process
* Migration path for existing applications: N/A
- Add publish script and process documentation.
- Add npm script to publish to npm.
- Update `build:dist` to use cross-env library.
- Updates `npmignore` to …
=> chore(release): Add release automation

package.json
As discussed in #56 dev-middleware introduced a breaking change on a minor version bump as we currently target minor version not patch.
Temporarily sets the `webpack-dev-middleware` version to patch from minor for updates until proper unit tests are in place and the issue can be addressed with the middleware team.
* Impact:
* Github Issue(s) this is regarding: #56 
Resolves #56
=> chore(deps): Use patch version of dev-middleware

README.md
Update README 
1. Update `testsContext` example to run the tests in a more of a safer manner.
2. Add example on how to run a single test file with karma-webpack.
This way we can run single test file (it's faster and much better when you write new tests).
For example:
` npm test --single_file=**/my-specific-spec.js`
=> [UPDATE] how to run a single test file

package.json
Resolves #186
//cc @MikaAK - This will need to be published for those wanting to use the Webpack Release Cnadidate
=> chore(package): allow Webpack 2.2.0 rc as peerDep

src/karma-webpack.js
The fix in https://github.com/webpack-contrib/karma-webpack/pull/208 (#69, #40) didn't work. When creating new files that match the globbing pattern in karma.config, the watcher crashes and needs a manual restart. 
Watcher doesn't crash when creating new files :)
In continuation to #225 :)
Tried to wrap my head around the contributing guide, but ran into problems. If you need me to update anything please let me know.
=> fix: readFile (windows)

src/karma-webpack.js, test/unit/plugin.test.js
- Duplicate of https://github.com/webpack-contrib/karma-webpack/pull/215
A proper error is given
---
- Fixes https://github.com/webpack-contrib/karma-webpack/issues/214
- Duplicate of https://github.com/webpack-contrib/karma-webpack/pull/215
> edited by @michael-ciniawsky (Formatting)
=> fix: pass on error to callback for better error messages

src/karma-webpack.js
Because other plugins (such as https://github.com/gjurgens/karma-renamer-preprocessor) may change the path.
If this plugin is used with https://github.com/gjurgens/karma-renamer-preprocessor and `singleRun` is `false`, it fails on subsequent builds as it is looking at the renamed path, not the original one.
If another plugin changes the path it won't effect how this works.
=> fix: use `file.originalPath` instead of `file.path`

package.json, src/mocha-env-loader.js
When mocha is wrapped and a sourcemap is present, the `mocha-env-loader` [tries to call `SourceNode.fromSourceWithMap(content, map)`](https://github.com/webpack-contrib/karma-webpack/blob/4701b62d9e99caeb8497144743f9ec010538cf77/src/mocha-env-loader.js#L16).
The `SourceNode.fromSourceWithMap()` function isn't defined [in `source-map@0.1.41`](https://github.com/mozilla/source-map/blob/0.1.41/lib/source-map/source-node.js) (I'm not sure if it was ever part of that library).
I've updated the dependency to `source-map@0.5.6` and adapted the code to the new API.
This gets rid of the `TypeError: SourceNode.fromSourceWithMap is not a function` from the log and reveals `Error: callback(): The callback was already called.` instead.  Assuming the intention was to return after calling the callback, …
=> fix: work with source maps when wrapped (`mocha-env-loader`)

src/karma-webpack.js
From https://github.com/webpack-contrib/karma-webpack/issues/230:
> Any plugin trying to write to assets folder will fail because karma webpack rewrites webpackOptions.output like so.
``` javascript
webpackOptions.output.path = '/_karma_webpack_/' + indexPath;
webpackOptions.output.publicPath = '/_karma_webpack_/' + publicPath;
```
> Since that path /_karma_webpack_/... has never existed the plugin which tries to write to asset folder will fail with ENOENT can't open file error.
Instead of using a `_karma_webpack_` directory in root, it the plugin …
=> fix: use `os.tmpdir()` to safely store `_karma_webpack_`

src/karma-webpack.js
Prior to #279, the following paths would always end with a slash:
- `webpackOptions.output.publicPath`
- `webpackOptions.output.publicPath`
- `webpackMiddlewareOptions.publicPath`
Fixes #284
`webpackOptions.output.publicPath`, `webpackOptions.output.publicPath` and `webpackMiddlewareOptions.publicPath` do not always include a trailing slash, as they did prior to #279.
`webpackOptions.output.publicPath`, `webpackOptions.output.publicPath` and `webpackMiddlewareOptions.publicPath` will always include a trailing slash.
**Does this PR introduce a …
=> fix(karma-webpack): ensure webpack `output` paths include a trailing slash

src/karma-webpack.js, test/unit/plugin.test.js
When running a long test suite as a single run, if you make changes to any of the files during the run, webpack will start recompiling
Webpack is only run in watch mode when running karma is not running with the `--single-run` flag
N/A
=> fix: disable `webpack` rebuilds on karma `--single-run`

src/karma-webpack.js
fix: convert index to string before passing to path.join to avoid TypeError
#286 
Converts an index to a string before it gets passed into path.join. It was previously being coalesced before 0616dda489d07f6a9bc3def1778dcef601411821
* Impact:
=> fix(karma-webpack): correctly coalesce `idx` (`{Number}`) in filepaths

.travis.yml
**What kind of change does this PR introduce?**
=> ci(.travis): update CI config

package.json
Install breaks on node < 8
Install is possible on node < 8
Resolves https://github.com/webpack-contrib/karma-webpack/issues/308
=> fix(package): downgrade `source-map` v0.7.0...0.5.6

package.json
- [*] Bugfix
`lib/karma-webpack.js` has the following line:
```js
var _toConsumableArray2 = require('babel-runtime/helpers/toConsumableArray');
```
When using `pnpm`, the babel-runtime is marked as a devDependency and therefore not included in the `node_modules`. Hence you get the following error:
```
27 02 2018 10:54:19.765:ERROR [config]: Invalid config file!
Error: Cannot find module 'babel-runtime/helpers/toConsumableArray'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require …
```
=> fix(package): use `babel-runtime` is a `dependency` (`dependencies`)

package-lock.json, package.json, src/karma-webpack.js
Doesn't support webpack 4's new plugin system
It supports webpack 4's new plugin system
* Impact: upgrades `webpack-dev-middleware` to latest, making node minimum version `6.11.5`
* Migration path for existing applications: update to webpack 4
Fixes #314
=> refactor(plugin): v3.0.0

package.json
Fixes #314 
- Update `webpack-dev-middleware` dependency
* Impact: the new major release is required since `webpack ^1.0.0` support has been dropped in `webpack-dev-middleware ^2.0.0`
- https://github.com/webpack/webpack-dev-middleware/releases/tag/v2.0.0
=> chore(package): update `webpack-dev-middleware` v1.12.0...2.0.6 (`dependencies`)

src/karma-webpack.js
For webpack 4, the presence of `optimization.splitChunks` and `optimization.runtimeChunk` causes karma to hang at the message 'Compiled successfully' (#322)
A workaround is for end-users to set these two properties to `false` in their webpack/karma configs; however it would make more sense to have `karma-webpack` do this in all cases, so that new users aren't left scratching their heads as to why their test suite won't run. 
- Fixes #322
- Fix (🏷 Patch)
=> fix(karma-webpack): disable `optimization` by default (`webpack >= v4.0.0`)

src/karma-webpack.js
=> fix(karma-webpack): allow `filename` and `chunkFilename` to be overridden (`config.output`)

src/karma-webpack.js
**What is the current behavior?**
During the refactoring, the method to add a file no longer returned `true`, causing the whole process to stall and karma not to start.
I'll add some integration tests ASAP.
=> fix(karma-webpack): `compilation` hangs when adding a file

src/karma-webpack.js
With #347 changes, now get error: `TypeError: Path must be a string. Received undefined`. After my research, there are 3 places will throw this error:
1. Two in the `readFile`, [L311](https://github.com/webpack-contrib/karma-webpack/blob/master/src/karma-webpack.js#L311), [L337](https://github.com/webpack-contrib/karma-webpack/blob/master/src/karma-webpack.js#L337), both are `this.outputs.get(file)`
--- the changes I made here is to map the file path to the entry path, so that can getting the file from the outputs. Example, changes from `test\unit\karma-test-shim` to `test/unit/karma-test-shim`
2. One in the `createPreprocesor` [L386](https://github.com/webpack-contrib/karma-webpack/blob/master/src/karma-webpack.js#L386), this line `webpackPlugin.outputs.get(filename);`
--- for this one, …
=> fix(karma-webpack): normalize paths (`windows`)

src/karma-webpack.js
This fixes issue #333 where a worker would fail to load due to a CORS issue. This change does NOT affect the write path for the webpack build, but the public path reflected in something like `<base href="/_karma_webpack/">`. 
The `os.tmpdir()` is stripped from the webpack's publicPath so that async assets are loaded correctly from a common domain avoiding CORS issues.
* Impact:
* Github …
=> fix(karma-webpack): don't include `os.tmpdir` (`options.publicPath`)

src/karma-webpack.js
uplift fix multiple output files to 4.x branch 
21 09 2018 23:54:23.585:ERROR [karma]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
=> [v4.x] fix(karma-webpack): handle multiple outputs correctly 

src/karma-webpack.js
Refer to https://github.com/webpack-contrib/karma-webpack/pull/357
The webpack output is not always the JS as first URL output
=> fix(karma-webpack): handle `outputPath` correctly

package.json
Date:   Fri Oct 19 16:08:37 2018 +0100
fix(npm packaging): restore prepare script in package.json so that npm install from github works
In commit 2a4d3b the prepare script was removed from package.json.  After that, it is no longer
possible to specify a github location in the project's package.json file to load a specific version
of the package from Github.  It should be possible to load the package using a command such as npm
install github:webpack-contrib/karma-webpack
=> fix(npm packaging): restore prepare script in package.json so that npm install from github works

package-lock.json, package.json, src/karma-webpack.js
In an attempt to remove dependencies that are barely used in popular npm packages, I have replaced lodash's `clone` method with an inline `clone` function with the same functionality. Based on that and provided that `lodash` is not used anywhere else in this package from what I can tell, the dependency on `lodash` has also been removed from `package.json`.
=> refactor(karma-webpack): Remove lodash from dependencies

src/karma-webpack.js
Taking over #366 (cleaned up PR and fixed another instance of `publicPath`). Fixes #362 (tested using steps provided by @johnnyreilly).
Public path is a URL, not a file path. It should not be created using `path.join`, which uses backslashes on Windows.
=> fix(karma-webpack): Fix publicPath to be Windows-compatible

src/karma-webpack.js, test/plugin.test.js
Unifies the color config between webpack and Karma. See https://github.com/webpack-contrib/karma-webpack/issues/332
- Fixes #332
=> feat(karma-webpack): unify `webpack` and  `karma` color config

src/karma-webpack.js
=> fix(karma-webpack): Do not unify "colors" property if webpack "stats" is a string

lib/KarmaWebpackController.js
In order to support dynamic imports we add all their contents to
the main bundle as well.
If you use `import('./foo.js').then()` webpack will by default create different chunks.
As they are not auto served by karma we add the dynamic content to the main bundle as well.
=> fix: add dynamic imports to main bundle

README.md, lib/KarmaWebpackController.js, lib/karma-webpack.js
currently, karmas watch retriggers builds and we have a debounce to mitigate that.
However, when watching is wanted that doesn't work.
=> so disable karma watch mode
=> get rid of the debounce
=> use only webpacks watch
=> fix(karma-webpack): disable karma watch; use webpack watch only

lib/karma-webpack.js
Karma runner didn't work with the v5.0.0-alpha.1 of this preprocessor on Windows machines.
This solves https://github.com/webpack-contrib/karma-webpack/issues/396
=> fix(karma-webpack):  normalize paths to be compatible with windows

lib/karma-webpack.js
fixes https://github.com/webpack-contrib/karma-webpack/issues/400
adds a hash to the webpack entry list so same filenames can exist.
=> fix: allow for same filenames to be added

package.json
Build is now outputting to the `dist/` folder and `package.json` was targeted at `lib/`, this fixes that
Closes #415, #416
=> fix(package): point to dist instead of lib

src/karma-webpack.js
Error is thrown if no `webpackMiddleware`. You can see [here](https://github.com/Profiscience/knockout-contrib/pull/184/commits/2d1b0a8eff0e388a5814f983dd8e020cf1876ff8) the change that makes the CI pass again.
N/A
Regression introduced in 4.0.0
=> fix(karma-webpack): don't error when webpackMiddleware config not provided

test/plugin.test.js
Quickly add some tests to prevent regressions like #418 from happening again (this will fail CI until that PR is merged)
=> test(plugin): add tests to prevent some regressions

package.json, test/integration/scenarios/basic-setup/basic-setup.test.js
chore(test): fix testing on linux
Some systems require the CHROME_BIN env
variable to be set for karma to hook
into the chrome binary for testing.
I noticed this while setting up
karma-webpack on my linux desktop.
Fixes N/A
This allows karma-webpack tests to run in certain linux environments where CHROME_BIN is not set automatically
N/A
N/A
=> Year of the linux desktop

README.md, lib/KarmaWebpackController.js, test/integration/scenarios/basic-setup/basic-setup.test.js
fix(controller): add entropy to default dir
This adds a random number to the end of the
default karma_webpack directory. This will
prevent projects running multiple instances
of karma webpack in parallel from stepping
on one another.
Fixes #465
Currently users trying to run multiple instances of karma-webpack will run into issues because the default
project directory is a static temporary directory. To fix this we add some random numbers to the end of the
directory so different builds running in parallel won't step on one another.
N/A
N/A
=> fix(controller): add entropy to default dir

lib/karma-webpack.js, lib/karma/karmaConfigValidator.js, test/integration/scenarios/basic-setup/basic-setup.test.js, test/unit/util/karmaConfigValidation.test.js
fix(preprocess): auto fix missing webpack framework
this is an issue that comes up often. As this is
something that karma-webpack needs to function,
we will automatically fix the configuration on
the fly and emit a warning that the change was
made.
Fixes N/A
adding 'webpack' in the karma configuration is a new requirement in v5 that is often overlooked.
as this is required and the plugin will not work without this, we will fix the configuration on the fly
and emit a warning stating that the change was made.
N/A
N/A
=> fix(preprocess): auto fix missing webpack framework

test/integration/scenarios/basic-setup/basic-setup.test.js
in newer versions of node, the promise
will never resolve if errors aren't
specifically handled. This can cause
tests to hang indefinitely.
Fixes N/A
This prevents integration test failures from hanging indefinitely.
N/A
N/A
=> fix(test): handle scenario test rejection

README.md
* Added myself as a maintainer
* Removed scary warning about webpack
framework as we handle this better
* Removed comment about internals
Fixes N/A
N/A
N/A
=> change(readme): made minor adjustments

lib/karma-webpack/controller.js, test/integration/scenarios/basic-setup/custom-output-path.test.js
this prevents karma-webpack from failing and also
prints out a useful error message explaining why
the webpack output.filename is ignored.
Fixes N/A
N/A
N/A
=> fix(config): force default output.filename

lib/karma-webpack/controller.js, lib/karma-webpack/preprocessor.js, test/integration/scenarios/basic-setup/custom-entry-path.test.js
karma-webpack will no longer crash when an entry
option is set in webpack config, instead a warning
will be thrown and the property will be ignored
for the time being.
Fixes N/A
N/A
N/A
=> fix(config): ignore entry options

test/unit/karma-webpack/controller.test.js
as it turns out os.tmpdir() is a function for a
reason :p. this changes the test to NOT use the
hardcoded tmp dir, but instead just use os.tmpdir
so that tests under other OSs will still pass.
Fixes N/A
N/A
N/A
=> fix(test): don't use hardcoded tmp directory

lib/webpack/plugin.js
I'm getting `no such file or directory` error from `karma-webpack`:
```
ERROR [karma-server]: Error: ENOENT: no such file or directory, open 13 07 2021 21:35:45.728:ERROR [karma-server]: Error: ENOENT: no such file or directory, open '/var/folders/fd/17654frj3379vn3wr07k_s_000jyn1/T/_karma_webpack_209189/../../../../../../Users/feiyangc/Projects/firebase-js-sdk/packages/logger/dist/src/logger.d.ts'
at Object.openSync (fs.js:476:3)
at Object.readFileSync (fs.js:377:35)
at /Users/feiyangc/Projects/firebase-js-sdk/node_modules/karma-webpack/lib/webpack/plugin.js:24:66
at Array.forEach (<anonymous>)
at /Users/feiyangc/Projects/firebase-js-sdk/node_modules/karma-webpack/lib/webpack/plugin.js:17:29
at Hook.eval [as callAsync] (eval at create …
```
=> fix(webpack): use path.resolve to create file path

lib/karma-webpack/preprocessor.js, test/integration/scenarios/basic-setup/basic-exclude.test.js, test/integration/scenarios/basic-setup/custom-output-path.test.js, test/integration/scenarios/basic-setup/js-test-passes.js, test/unit/karma-webpack/controller.test.js
resolves (#520)
if you were excluding things you wanted to be run it will really be excluded now
fixed some tests that did not pass when running on windows
i also couldn't find an easy way to confirm that it had not passed the config file as an entry point in the tests. for solving #520 this is reliant on karma having added the config file to the exclude list
=> fix(karma-webpack) respect exclude list from config (#520)

package.json
this will be the new baseline for 6.0.0
Fixes N/A
=> chore: set node version to >= 18

package.json
this brings minimatch up to the latest working major version, the next bump will require some reworking
Fixes N/A
=> chore: upgrade minimatch to 8

lib/karma-webpack/controller.js
This prevents a warning that occurs when output.filename is set to '[name].js'. Because this is the default, there is no need to warn the user as no change will happen.
Fixes #550
=> fix(controller): don't warn if name is default

lib/karma-webpack/preprocessor.js, package.json
this updates minimatch to 9, which no longer has a default export and must be destructured.
Fixes N/A
=> chore: update minimatch to 9

package-lock.json, package.json
this is not used in either the project or tests and has a strict dependency on webpack 4.
this also bumps the package lock and removes yarn
lock
Fixes N/A
=> chore: remove webpack-contrib-defaults

package.json
this website for nodesecurity.io is dead as a doornail I think its time to remove this.
Fixes N/A
=> chore: remove nsp

README.md
seemed disrespectful 🤷
Fixes N/A
=> chore: fix maintainers images being squished

README.md
This reverts commit 701a082ce4765bffb151472d40406143c98c6215.
apparently github sanitizes styles :(
=> Revert "chore: fix maintainers images being squished (#576)"

lib/karma-webpack/controller.js
this will often break the inner workings of karma-webpack due to a number of issues coming in about this in particular it has been decided that it is best to ignore these kinds of customization and log a warning that they are discarded
Fixes #491
=> fix(controller): disallow custom optiomization

lib/karma-webpack/controller.js
```
we should not dictate this behavior, just warning
users that this may lead to unexpected behavior
should suffice.
```
Fixes #587
=> fix(controller): remove breaking change to optimization
